fix keypress_windows: use LPCWSTR (const wchar_t*) instead of LPCTSTR (const char*)
fixes this error:
D:\a\qMasterPassword\qMasterPassword\src\keypress_windows.cpp(99,5): error C2664: 'void CKeyboardSimulator::TextEntry(LPCTSTR)': cannot convert argument 1 from 'const _Elem *' to 'LPCTSTR' [D:\a\_temp\build\qMasterPassword.vcxproj]