fix windows: ensure correct include order
- stdafx.h needs to be first
- windows.h before winuser.h

Fixes this error on Windows:
fatal  error C1189: #error:  "No Target Architecture"